apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-tls
spec:
  secretName: {{ .Chart.Name }}-tls
  duration: 175200h
  renewBefore: 72h
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
  isCA: true
  issuerRef:
    name: {{ .Chart.Name }}
    kind: ClusterIssuer