apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
  {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}