apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Chart.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.email }}
    privateKeySecretRef:
      name: {{ .Chart.Name }}-tls
    solvers:
      - http01:
          ingress:
            class: nginx
