apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicHJhbW9zbyIsInBhc3N3b3JkIjoiZ2hwX2U0dGduRVNSVVRnaG8zb1dzbFpBaWxxV2VGRFdJNDFING54biIsImF1dGgiOiJjSEpoYlc5emJ6cG5hSEJmWlRSMFoyNUZVMUpWVkdkb2J6TnZWM05zV2tGcGJIRlhaVVpFVjBrME1VZzBibmh1In19fQ==
type: kubernetes.io/dockerconfigjson